### ISSUE TITLE
CRC32 instruction requires compile option “-march=armv8-a+crc”

### ISSUE THREAD

**Issue by leeq2016** [kunpengcompute/gzip#2]
https://github.com/kunpengcompute/gzip/blob/89365055899959248c16f524ab71ea856a321c7c/util.c#L40

CRC32 instruction requires compile option “-march=armv8-a+crc”

**Comment by leeq2016** [comment]
https://github.com/kunpengcompute/gzip/pull/3

**Comment by derekpush** [comment]
It's right that it should add compile option in aarch64. 
good commit and PR is merged.
